
###

GET http://localhost:8060/api/v1/book/all

###

GET http://localhost:8060/api/v1/book/1

###

GET http://localhost:8060/api/v1/book/2

###

GET http://localhost:8060/api/v1/book/3

###

GET http://localhost:8060/api/v1/book/4

###

GET http://localhost:8060/api/v1/book/5

###

GET http://localhost:8060/api/v1/review/all

###

GET http://localhost:8060/api/v1/review/1

###

GET http://localhost:8060/api/v1/review/2

###

GET http://localhost:8060/api/v1/review/3

###

GET http://localhost:8060/api/v1/review/4

###

GET http://localhost:8060/api/v1/review/5

###


